### PR TITLE
Update injection.js

### PR DESCRIPTION
**Pull request by Entity378**
I fixed the Injection , but without the webhook protector option. 
Obviously, i only fixed the "clean" version and not the "obfuscated" one.

### CODE REVIEW

**Review by Smug246 — CHANGES_REQUESTED** [review]
remove the obfuscated function in there im not stupid

**Comment by KDot227** [comment]
> remove the obfuscated function in there im not stupid

idk if I'm slow but ion see no obfuscated stuff

**Comment by Smug246** [comment]
line 620. that's obfuscated no?

**Comment by KDot227** [comment]
no lol compare it with 

> line 620. that's obfuscated no?

no lol compare it with deleted line 464

**Comment by KDot227** [comment]
> https://github.com/Entity378/Bone-Skewer-Grabber

💀

**Comment by Smug246** [comment]
> no lol compare it with 
> 
> 
> 
> > line 620. that's obfuscated no?
> 
> 
> 
> no lol compare it with deleted line 464


oh ye mb.

**Pull request closed without merging**
